[package]
name = "minecraft-game-logic"
version = "0.1.0"
authors = ["Geert van Ieperen <ieperen3039>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand_core = "0.9.3"