[package]
name = "minecraft-protocol"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

[dependencies]
minecraft-protocol-derive = { path = "../minecraft-protocol-derive" }

[features]
all-packets = []
