[package]
name = "minecraft-external"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>", "Geert van Ieperen <ieperen3039>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = {version="1.0", features=["derive"]}
minreq = {version="2.3", features=["https"]}
